
# User.create!([
#   {username: "SNix", password_digest: "$2a$12$ezYomPVL7ygDDaWVeJXgrezxyN.d3dONALp/MpY51BsrUekHXy6hG", first_name: "Steph", last_name: "Nixon", email: "snixon@gmail.com"},
#   {username: "amyers", password_digest: "$2a$12$3vAJwyJCUL1eEeNsYGhimex2S2UJAAbvnBXLKWxrW4gy5pbP6mtJq", first_name: "Amy", last_name: "Myers", email: "amyers@gmail.com"},
#   {username: "carl", password_digest: "$2a$12$mbB2qTlairNFv1nHavPwae6VE68XI08GTiZ5r./QOdjoX82TUko76", first_name: "Carl", last_name: "Hauck", email: "carl@gmail.com"},
#   {username: "JakeSnake", password_digest: "$2a$12$jVRut4Zp.wTZKzRlp408/.kRWAn92dVIH8YY9yJdR3PUk/aU9djEq", first_name: "Jacob", last_name: "Doukas", email: "JakeSnake@gmail.com"},
#   {username: "Betty", password_digest: "$2a$12$M9Bf4gySRSi1vRtsyfDopuLwqg.Lfe8Ij5lDUI.ZW0eXPWUQKQIM2", first_name: "Betty", last_name: "Doukas", email: "Betty@gmail.com"},
#   {username: "alex", password_digest: "$2a$12$a13WO.jlr7zPrmWofrV6HeIh5RwBOaeVQDOl0a8Sc.Ms7ZCSALqaK", first_name: "Alex", last_name: "Rosales", email: "alex@gmail.com"},
#   {username: "beccabagels", password_digest: "$2a$12$oKVZ4jlk3Gko8hfdpE/.CuWtnaqhNVWawkZmaD8lUYiZFnJCV9vnG", first_name: "Becca", last_name: "Doukas", email: "becca@gmail.com"}
# ])

Ad.create!([
  {title: "Burritto Succulent", user_id: 5, description: " I have an adorable burrito succulent potted in a 3 inch ceramic pot. These guys grow like crazy and will trail over the pot. They're great to hang!  Let me know if you have any questions. ", image_url: "https://res.cloudinary.com/dzx2kuqwt/image/upload/v1596668993/f3xcsqxwtjndawz4qowb.jpg"},
  {title: "Easy Elephant Bush", user_id: 5, description: " I have a great Elephant bush I'd love to pass on! I've had the plant for a year and it's already grown so much! It's perfect to hang or put on a table. ", image_url: "https://res.cloudinary.com/dzx2kuqwt/image/upload/v1596669271/gw0ypd6leocchaynaqxr.jpg"},
  {title: "Pink Begonia Clippings", user_id: 6, description: " I have a couple clippings of my pink begonia that have started to root in a glass of water. My original plant wouldn't stop growing and I thought I'd try propagation!! ", image_url: "https://res.cloudinary.com/dzx2kuqwt/image/upload/v1596721703/xoweaqklb8muy8bh320c.jpg"},
  {title: "Pink Orchid", user_id: 1, description: " This orchid has brought me joy for years! I'll be moving within the month and would love to give her a loving home! ", image_url: "https://res.cloudinary.com/dzx2kuqwt/image/upload/v1596670737/pg8otvnkvexpleegarrv.jpg"},
  {title: "Swiss Cheese Plant", user_id: 3, description: " I have a wonderful Swiss Cheese Plant (monstera deliciosa) that's outgrowing it's space. I have a clipping that I temporarily put in a nursery pot but this should be treated as a propagation.", image_url: "https://res.cloudinary.com/dzx2kuqwt/image/upload/v1596672511/ik0yvpjuh0urvdzjroyx.jpg"},
  {title: "Happy Pincushion", user_id: 3, description: " I have a 3 inch pot with 3 Happy Bean(Pincushion Peperomia) in it. One is a propagation from a another plant in the pot. These things grow like CRAZY and are great to propagate, especially cute gifts! ", image_url: "https://res.cloudinary.com/dzx2kuqwt/image/upload/v1596672773/lvkipqrvtaeptsyj5lkp.jpg"},
  {title: "Desert Pinwheel ", user_id: 3, description: "   I have a desert pinwheel rose that I’d love to share with a fellow plant lover! They’re great for bedding, can be kept indoors or outdoors! It’s requires a little more care so perfect if you’re trying to step up your plant game! ", image_url: "https://res.cloudinary.com/dzx2kuqwt/image/upload/v1596827085/p74bid5qmpo3aavx8xau.jpg"},
  {title: "Succulent assortment", user_id: 3, description: " I have three different succulents in a 3 inch pot together. The jade succulent is a recent cutting from a larger plant. It's starting to grow roots and is growing a crown but is very fragile. ", image_url: "https://res.cloudinary.com/dzx2kuqwt/image/upload/v1596678481/fhqw0wsqwsb5irko6okm.jpg"},
  {title: "Elephant Ear", user_id: 2, description: " I have had this beautiful elephant ear for about two years. With an upcoming cross country move I sadly have to part ways. Hope I can find her a good home!", image_url: "https://res.cloudinary.com/dzx2kuqwt/image/upload/v1596720840/r0l7rdcl9veiwsmwnwm6.jpg"},
  {title: "Moon Cactus", user_id: 2, description: " I have a great moon cactus! It comes in a nursery pot. I'd love to give her a new home! Let me know if you have any questions! ", image_url: "https://res.cloudinary.com/dzx2kuqwt/image/upload/v1596721127/cxpzkdkfrpgviztvdckb.jpg"}
])

Category.create!([
  {name: "Drop Off"},
  {name: "Pick Up"},
  {name: "Easy Care"},
  {name: "Medium Care"},
  {name: "Advanced Care"},
  {name: "Bright Light"},
  {name: "Low Light"},
  {name: "Pet Friendly"},
  {name: "Air Purifying"},
  {name: "Tropical"},
  {name: "Blooming"},
  {name: "Fern"},
  {name: "Succulent"},
  {name: "Vine"},
  {name: "Hanging Plant"},
  {name: "Herbs"},
  {name: "Tree"},
  {name: "Propogation"},
  {name: "Seeds"},
  {name: "Potted"}
])

AdCategory.create!([
  {category_id: 2, ad_id: 4},
  {category_id: 3, ad_id: 4},
  {category_id: 6, ad_id: 4},
  {category_id: 13, ad_id: 4},
  {category_id: 20, ad_id: 4},
  {category_id: 8, ad_id: 4},
  {category_id: 1, ad_id: 11},
  {category_id: 3, ad_id: 11},
  {category_id: 6, ad_id: 11},
  {category_id: 8, ad_id: 11},
  {category_id: 20, ad_id: 11},
  {category_id: 13, ad_id: 11},
  {category_id: 15, ad_id: 1},
  {category_id: 2, ad_id: 1},
  {category_id: 4, ad_id: 1},
  {category_id: 6, ad_id: 1},
  {category_id: 11, ad_id: 1},
  {category_id: 20, ad_id: 1},
  {category_id: 1, ad_id: 3},
  {category_id: 3, ad_id: 3},
  {category_id: 6, ad_id: 3},
  {category_id: 10, ad_id: 3},
  {category_id: 18, ad_id: 3},
  {category_id: 1, ad_id: 10},
  {category_id: 3, ad_id: 10},
  {category_id: 6, ad_id: 10},
  {category_id: 13, ad_id: 10},
  {category_id: 20, ad_id: 10},
  {category_id: 2, ad_id: 7},
  {category_id: 3, ad_id: 7},
  {category_id: 6, ad_id: 7},
  {category_id: 8, ad_id: 7},
  {category_id: 15, ad_id: 7},
  {category_id: 20, ad_id: 7},
  {category_id: 2, ad_id: 9},
  {category_id: 4, ad_id: 9},
  {category_id: 6, ad_id: 9},
  {category_id: 13, ad_id: 9},
  {category_id: 20, ad_id: 9},
  {category_id: 1, ad_id: 2},
  {category_id: 7, ad_id: 2},
  {category_id: 20, ad_id: 2},
  {category_id: 17, ad_id: 2},
  {category_id: 4, ad_id: 2},
  {category_id: 1, ad_id: 6},
  {category_id: 3, ad_id: 6},
  {category_id: 6, ad_id: 6},
  {category_id: 13, ad_id: 6},
  {category_id: 20, ad_id: 6},
  {category_id: 4, ad_id: 5},
  {category_id: 2, ad_id: 5},
  {category_id: 7, ad_id: 5},
  {category_id: 18, ad_id: 5},
  {category_id: 11, ad_id: 5},
  {category_id: 1, ad_id: 12},
  {category_id: 4, ad_id: 12},
  {category_id: 6, ad_id: 12},
  {category_id: 2, ad_id: 13},
  {category_id: 4, ad_id: 14},
  {category_id: 1, ad_id: 15},
  {category_id: 6, ad_id: 15}
])

Conversation.create!([
  {sender_id: 2, recipient_id: 2, ad_id: 1},
  {sender_id: 3, recipient_id: 1, ad_id: 1},
  {sender_id: 1, recipient_id: 5, ad_id: 4},
  {sender_id: 2, recipient_id: 3, ad_id: 3},
  {sender_id: 6, recipient_id: 3, ad_id: 10},
  {sender_id: 3, recipient_id: 5, ad_id: 4},
  {sender_id: 3, recipient_id: 2, ad_id: 2},
  {sender_id: 5, recipient_id: 3, ad_id: 10},
  {sender_id: 6, recipient_id: 5, ad_id: 11},
  {sender_id: 3, recipient_id: 2, ad_id: 2}
])
Message.create!([
  {body: " Hi! Is your plant still available?", user_id: 2, conversation_id: 1},
  {body: " Yes it is, are you free to pick it up this week?", user_id: 1, conversation_id: 1},
  {body: " I am on Tuesday!", user_id: 2, conversation_id: 1},
  {body: " Great! See you then!", user_id: 1, conversation_id: 1},
  {body: " Hello! How big is the swiss chesse plant?", user_id: 3, conversation_id: 3},
  {body: " Hi! The pot is 18 in and it's 2 feet high", user_id: 6, conversation_id: 3},
  {body: " Awesome! The perfect height! Where are you located? I see it's a pick up.", user_id: 3, conversation_id: 3},
  {body: " I'm at Naper and 75th right by the Mariano's", user_id: 6, conversation_id: 3},
  {body: " Not too far! Tomorrow works, see you then!!! ", user_id: 3, conversation_id: 3},
  {body: " Awesome!", user_id: 6, conversation_id: 3},
  {body: " I love this orchid!!! ", user_id: 3, conversation_id: 4},
  {body: " Thank you!! Would you like to adopt it?", user_id: 1, conversation_id: 4},
  {body: " This succulent is so cute! I've never seen one like it! What part of town are you located? I see you would like it picked up. ", user_id: 1, conversation_id: 5},
  {body: " I've always wanted a swiss cheese plant and have been dying to try propagation!! When can you drop it off?", user_id: 1, conversation_id: 6},
  {body: " I love this plant!!! Is it still available? ", user_id: 2, conversation_id: 8},
  {body: " This is so cute and I love the name!! I'm new to the plant mom love and hoping to find something easy but cute! What's your schedule like this week?", user_id: 6, conversation_id: 9},
  {body: " This is so cute! When are you free this week?", user_id: 3, conversation_id: 11},
  {body: " Hello I love your plant! ", user_id: 2, conversation_id: 12},
  {body: " Yes it is! It started as a propagation but is starting to root nicely! ", user_id: 3, conversation_id: 8},
  {body: " Awesome! Are you free this week for the swap?", user_id: 2, conversation_id: 8},
  {body: " I'm free every day after 5 pm. Is there a day that works best for you? ", user_id: 3, conversation_id: 9},
  {body: " This plant is so interesting and hearty, I've never seen anything like it! Are you free this week? I'm in Lakeview ", user_id: 3, conversation_id: 13},
  {body: " I am, I'm in Buena Park so right there!! How does Wednesday sound??", user_id: 3, conversation_id: 13},
  {body: " Yes it does! I'll see you then! ", user_id: 3, conversation_id: 13},
  {body: " This looks so cool! Are you free this week?", user_id: 3, conversation_id: 14},
  {body: " Yes I am! How about Tuesday at 6 pm?", user_id: 2, conversation_id: 14},
  {body: " Fake", user_id: 2, conversation_id: 15},
  {body: " Yes I would! I've always wanted an orchid! Are you free this week? ", user_id: 3, conversation_id: 4},
  {body: " Yes I am! Tuesday after 5 pm works for me! Is that good for you?", user_id: 3, conversation_id: 8},
  {body: " Yes I am! How does Tuesday sound? I'm around all day!", user_id: 1, conversation_id: 4},
  {body: " Yes I would. I'm in the loop. Does that work for you? ", user_id: 5, conversation_id: 5},
  {body: " I'm free on Tuesday and Thursday all day. Which day works best for you?", user_id: 5, conversation_id: 11},
  {body: " Is the pincushion still available? I'm looking for something easy to grow as I'm new to this and love the interesting shape. ", user_id: 5, conversation_id: 16},
  {body: " How about Thursday at 6 pm?", user_id: 6, conversation_id: 9},
  {body: " This plant is so cool! Are you free this week to drop it off?", user_id: 6, conversation_id: 17},
  {body: " Perfect! I'll stop by around 12 pm.", user_id: 3, conversation_id: 4},
  {body: " Perfect! I'll see you then!", user_id: 3, conversation_id: 9},
  {body: " Perfect!!!", user_id: 3, conversation_id: 14},
  {body: " How about Thursday at 3 pm?", user_id: 3, conversation_id: 11},
  {body: " Yes it is! It's super easy to grow and so cool! It's great for propagation too! I'm busy this week but how about next week?", user_id: 3, conversation_id: 16},
  {body: " That's great! I'll see you then! ", user_id: 5, conversation_id: 11},
  {body: " That works for me! How about next Monday evening?", user_id: 5, conversation_id: 16},
  {body: " Yes I am! What part of town are you in?", user_id: 5, conversation_id: 17},
  {body: " Great! ", user_id: 6, conversation_id: 9},
  {body: " I'm in the South Loop. Does noon on Thursday okay?", user_id: 6, conversation_id: 17},
  {body: " Yes it is! See you then!!! ", user_id: 2, conversation_id: 8},
  {body: " Awesome!!!!", user_id: 3, conversation_id: 8},
  {body: " Hi! I love your plant! \n", user_id: 3, conversation_id: 21},
  {body: " Thanks so much!", user_id: 2, conversation_id: 21}
])

